RND203-322: Add AR_SREV_9271 macro
Mobica/freebsd-src pull request #38
Opened 2024-02-08 16:19 UTC by Rafal-Litwinski-Mobica

2024-02-09 11:18 UTC, Mikolaj-Filar-Mobica approved these changes

2024-02-09 14:18 UTC, Mikolaj-Filar-Mobica commented on sys/dev/ath/ath_hal/ar5416/ar5416reg.h
> +#define	AR_SREV_9271(_ah)
Lack of `\` end of line

2024-02-09 14:19 UTC, Mikolaj-Filar-Mobica requested changes
Missing \ at the end of line

2024-02-09 14:22 UTC, Mikolaj-Filar-Mobica commented on sys/dev/ath/ath_hal/ar5416/ar5416reg.h
> +#define AR_XSREV_VERSION_K2         0x140	/* K2 (AR9160) */
AR9160?

2024-02-09 14:35 UTC, Rafal-Litwinski-Mobica commented on sys/dev/ath/ath_hal/ar5416/ar5416reg.h
> +#define	AR_SREV_9271(_ah)
fixed

2024-02-09 14:35 UTC, Rafal-Litwinski-Mobica commented on sys/dev/ath/ath_hal/ar5416/ar5416reg.h
> +#define AR_XSREV_VERSION_K2         0x140	/* K2 (AR9160) */
fixed

2024-02-12 07:26 UTC, Mikolaj-Filar-Mobica approved these changes

2024-02-12 07:53 UTC, nzulinski-mobica approved these changes

2024-02-12 08:11 UTC, merged